- name: Read secret
  hosts: localhost
  tasks:
    -name: read a kv2 secret
  ansible.builtin.debug:
    msg: "{{ secrets.mysql }}"
    vars:
    secrets:"{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-dev/data/mysql token={{token}} url=https://vault-3.80.182.210:8200 validate_certs=false') }}"
