

- name: disabling old version of nodejs
  ansible.builtin.shell : dnf module disable nodejs -y

- name: enabling latest version of nodejs
  ansible.builtin.shell : dnf module enable nodejs:20 -y

- name: installing nodejs
  ansible.builtin.dnf :
    name : nodejs
    state : present

- name: adding user
  ansible.builtin.user :
    name : expense_user

- name: config file copy
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: import role
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq.yml

- name: downloading npm dependencies
  community.general.npm:
    path : /app

- name: install mysql client & mysql python
  ansible.builtin.dnf :
    name :
      - mysql
      - python3.11-PyMySQL
    state : present

#- name: import mysql schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/schema/backend.sql
#    login_user: root
#    login_password: ExpenseApp@1
#    login_host: mysql-dev.saidevops79.online

- name: load schema
  ansible.builtin.shell : mysql -h mysql-dev.saidevops79.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: start backend service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled : true
    daemon_reload: true