- name: set prompt
  ansible.builtin.shell: set-prompt mysql

- name : installing mysql
  ansible.builtin.dnf :
    name : mysql-server
    state : present

- name: start mysql  and enabling service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: set root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1