component: backend
app_path: /app
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-{{dev}}/data/mysql token={{vault_token}} url=https://vault-3.80.182.210:8200 validate_certs=false') }}"