- name: removing old application directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: creating application directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory

- name: download content & extract
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_path }}"
    remote_src: yes